# Generated by Django 3.1.4 on 2020-12-28 08:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20201228_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='phone',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Your phone no must be 10 digits and numeric only.', regex='^[0-9]{10}$')]),
        ),
    ]
