# Generated by Django 3.1.4 on 2020-12-28 10:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_auto_20201228_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.CharField(default=datetime.datetime(2020, 12, 28, 10, 25, 21, 321461, tzinfo=utc), max_length=1500),
            preserve_default=False,
        ),
    ]
