# Generated by Django 3.1.4 on 2020-12-30 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_auto_20201228_1616'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='first_name',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='myuser',
            old_name='last_name',
            new_name='lastname',
        ),
    ]
