# Generated by Django 3.1.4 on 2020-12-30 05:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_auto_20201230_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='confirm_password',
            field=models.CharField(default=datetime.datetime(2020, 12, 30, 5, 53, 42, 814423, tzinfo=utc), max_length=16),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='myuser',
            name='password',
            field=models.CharField(max_length=16),
        ),
    ]
