# Generated by Django 3.1.4 on 2021-01-05 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_auto_20210105_0942'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMTPTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('backend', models.CharField(max_length=500)),
                ('host', models.CharField(max_length=500)),
                ('port', models.IntegerField()),
                ('tls', models.BooleanField(default=True)),
                ('user', models.EmailField(max_length=200)),
                ('user_password', models.CharField(max_length=20)),
            ],
        ),
    ]
