# Generated by Django 3.1.4 on 2021-01-05 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_smtptable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smtptable',
            name='name',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
